import 'model.dart';

final List<Books> demoBooks = [
  Books(
    id: '1',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    year: 1813,
    genre: 'Romance',
    tropes: ['Enemies to lovers'],
  ),
  Books(
    id: '2',
    title: '1984',
    author: 'George Orwell',
    year: 1949,
    genre: 'Dystopian',
    tropes: ['Surveillance', 'Totalitarianism'],
  ),
  Books(
    id: '3',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    year: 1960,
    genre: 'Southern Gothic',
    tropes: ['Coming of age', 'Social justice'],
  ),
  Books(
    id: '4',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    year: 1925,
    genre: 'Tragedy',
    tropes: ['Unrequited love', 'The American Dream'],
  ),
  Books(
    id: '5',
    title: 'Moby-Dick',
    author: 'Herman Melville',
    year: 1851,
    genre: 'Adventure',
    tropes: ['Obsession', 'Man vs. nature'],
  ),
  Books(
    id: '6',
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    year: 1869,
    genre: 'Historical Fiction',
    tropes: ['Epic saga', 'Napoleonic Wars'],
  ),
  Books(
    id: '7',
    title: 'Crime and Punishment',
    author: 'Fyodor Dostoevsky',
    year: 1866,
    genre: 'Psychological Fiction',
    tropes: ['Guilt', 'Redemption'],
  ),
  Books(
    id: '8',
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    year: 1951,
    genre: 'Bildungsroman',
    tropes: ['Alienation', 'Teen angst'],
  ),
  Books(
    id: '9',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    year: 1937,
    genre: 'Fantasy',
    tropes: ['Reluctant hero', 'Quest'],
  ),
  Books(
    id: '10',
    title: 'Jane Eyre',
    author: 'Charlotte Brontë',
    year: 1847,
    genre: 'Gothic Fiction',
    tropes: ['Orphaned heroine', 'Forbidden love'],
  ),
  Books(
    id: '11',
    title: 'Brave New World',
    author: 'Aldous Huxley',
    year: 1932,
    genre: 'Dystopian',
    tropes: ['Totalitarianism', 'Genetic engineering'],
  ),
  Books(
    id: '12',
    title: 'The Odyssey',
    author: 'Homer',
    year: -800,
    genre: 'Epic Poetry',
    tropes: ['Heroic journey', 'Divine intervention'],
  ),
  Books(
    id: '13',
    title: 'The Brothers Karamazov',
    author: 'Fyodor Dostoevsky',
    year: 1880,
    genre: 'Philosophical Fiction',
    tropes: ['Moral conflict', 'Family drama'],
  ),
  Books(
    id: '14',
    title: 'Wuthering Heights',
    author: 'Emily Brontë',
    year: 1847,
    genre: 'Gothic Fiction',
    tropes: ['Tragic love', 'Revenge'],
  ),
  Books(
    id: '15',
    title: 'The Picture of Dorian Gray',
    author: 'Oscar Wilde',
    year: 1890,
    genre: 'Philosophical Fiction',
    tropes: ['Vanity', 'Moral decay'],
  ),
  Books(
    id: '16',
    title: 'The Grapes of Wrath',
    author: 'John Steinbeck',
    year: 1939,
    genre: 'Historical Fiction',
    tropes: ['Great Depression', 'Social injustice'],
  ),
  Books(
    id: '17',
    title: 'Frankenstein',
    author: 'Mary Shelley',
    year: 1818,
    genre: 'Gothic Fiction',
    tropes: ['Mad scientist', 'Creation'],
  ),
  Books(
    id: '18',
    title: 'Dracula',
    author: 'Bram Stoker',
    year: 1897,
    genre: 'Horror',
    tropes: ['Vampire', 'Immortality'],
  ),
  Books(
    id: '19',
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    year: 1954,
    genre: 'Fantasy',
    tropes: ['Epic quest', 'Good vs. evil'],
  ),
  Books(
    id: '20',
    title: 'The Stranger',
    author: 'Albert Camus',
    year: 1942,
    genre: 'Existential Fiction',
    tropes: ['Absurdism', 'Alienation'],
  ),
  Books(
    id: '21',
    title: 'Les Misérables',
    author: 'Victor Hugo',
    year: 1862,
    genre: 'Historical Fiction',
    tropes: ['Redemption', 'Social justice'],
  ),
  Books(
    id: '22',
    title: 'The Bell Jar',
    author: 'Sylvia Plath',
    year: 1963,
    genre: 'Semi-autobiographical Fiction',
    tropes: ['Mental illness', 'Identity'],
  ),
  Books(
    id: '23',
    title: 'The Trial',
    author: 'Franz Kafka',
    year: 1915,
    genre: 'Existential Fiction',
    tropes: ['Bureaucracy', 'Surrealism'],
  ),
  Books(
    id: '24',
    title: 'The Sun Also Rises',
    author: 'Ernest Hemingway',
    year: 1926,
    genre: 'Modernist Fiction',
    tropes: ['Lost generation', 'Expatriates'],
  ),
  Books(
    id: '25',
    title: 'The Old Man and the Sea',
    author: 'Ernest Hemingway',
    year: 1952,
    genre: 'Literary Fiction',
    tropes: ['Man vs. nature', 'Perseverance'],
  ),
];
