// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBepnKNmalBGb4Vqk8UJUjLTX7qMYigSs',
    appId: '1:525406215989:web:9f89a13db8ff3d799db67c',
    messagingSenderId: '525406215989',
    projectId: 'bookapp-ce0b3',
    databaseURL:'//bookapp-ce0b3-default-rtdb.firebaseio.com',
    authDomain: 'bookapp-ce0b3.firebaseapp.com',
    storageBucket: 'bookapp-ce0b3.firebasestorage.app',
    measurementId: 'G-MHR5J2KQ26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLB4S7Yvq0X4SUFGp3t75gpLCWeMp29xg',
    appId: '1:525406215989:android:4ab0a264a5f3cd099db67c',
    messagingSenderId: '525406215989',
    projectId: 'bookapp-ce0b3',
    databaseURL:'//bookapp-ce0b3-default-rtdb.firebaseio.com',
    storageBucket: 'bookapp-ce0b3.firebasestorage.app',
  );
}
